package ch.pledarigrond.lucene.util;

import ch.pledarigrond.common.data.lucene.FieldType;
import ch.pledarigrond.common.data.lucene.IndexedColumn;

import java.util.Arrays;
import java.util.List;

public class DatabaseFields {
    public static List<IndexedColumn> getDatabaseColumns() {
        return Arrays.asList(
                new IndexedColumn(FN.entryId),
                new IndexedColumn(FN.versionId),

                new IndexedColumn(FN.deStichwort, FieldType.STRING_SORTED),
                new IndexedColumn(FN.deStichwortSort, FieldType.INTEGER_SORTED),
                new IndexedColumn(FN.deSemantik),
                new IndexedColumn(FN.deSubsemantik, FieldType.STRING_SORTED),
                new IndexedColumn(FN.deGrammatik, FieldType.STRING_SORTED),
                new IndexedColumn(FN.deGenus, FieldType.STRING_SORTED),
                new IndexedColumn(FN.deTags),

                new IndexedColumn(FN.rmStichwort, FieldType.STRING_SORTED),
                new IndexedColumn(FN.rmStichwortSort, FieldType.INTEGER_SORTED),
                new IndexedColumn(FN.rmSemantik),
                new IndexedColumn(FN.rmSubsemantik, FieldType.STRING_SORTED),
                new IndexedColumn(FN.rmGrammatik, FieldType.STRING_SORTED),
                new IndexedColumn(FN.rmGenus, FieldType.STRING_SORTED),
                new IndexedColumn(FN.rmFlex),
                new IndexedColumn(FN.rmTags),
                new IndexedColumn(FN.inflectionType),
                new IndexedColumn(FN.inflectionSubtype),
                new IndexedColumn(FN.categories, FieldType.SEMICOLON_SEPERATED),
                new IndexedColumn(FN.deRedirect),
                new IndexedColumn(FN.rmRedirect),
                new IndexedColumn(FN.userComment),
                new IndexedColumn(FN.userEmail),
                new IndexedColumn(FN.rmEtymologie),
                new IndexedColumn(FN.examplesJson), // these are the examples serialized as JSON to store the data
                new IndexedColumn(FN.examplesRm, FieldType.TEXT, false), // these are the romansh examples, for search only
                new IndexedColumn(FN.examplesDe, FieldType.TEXT, false), // these are the german examples, for search only
                new IndexedColumn(FN.rmPronunciation),

                // verbs
                new IndexedColumn(FN.infinitiv),
                new IndexedColumn(FN.irregular),
                new IndexedColumn(FN.preschentsing1),
                new IndexedColumn(FN.preschentsing2),
                new IndexedColumn(FN.preschentsing3),
                new IndexedColumn(FN.preschentplural1),
                new IndexedColumn(FN.preschentplural2),
                new IndexedColumn(FN.preschentplural3),
                new IndexedColumn(FN.imperfectsing1),
                new IndexedColumn(FN.imperfectsing2),
                new IndexedColumn(FN.imperfectsing3),
                new IndexedColumn(FN.imperfectplural1),
                new IndexedColumn(FN.imperfectplural2),
                new IndexedColumn(FN.imperfectplural3),
                new IndexedColumn(FN.conjunctivsing1),
                new IndexedColumn(FN.conjunctivsing2),
                new IndexedColumn(FN.conjunctivsing3),
                new IndexedColumn(FN.conjunctivplural1),
                new IndexedColumn(FN.conjunctivplural2),
                new IndexedColumn(FN.conjunctivplural3),
                new IndexedColumn(FN.conjunctivimperfectsing1),
                new IndexedColumn(FN.conjunctivimperfectsing2),
                new IndexedColumn(FN.conjunctivimperfectsing3),
                new IndexedColumn(FN.conjunctivimperfectplural1),
                new IndexedColumn(FN.conjunctivimperfectplural2),
                new IndexedColumn(FN.conjunctivimperfectplural3),
                new IndexedColumn(FN.cundizionalsing1),
                new IndexedColumn(FN.cundizionalsing2),
                new IndexedColumn(FN.cundizionalsing3),
                new IndexedColumn(FN.cundizionalplural1),
                new IndexedColumn(FN.cundizionalplural2),
                new IndexedColumn(FN.cundizionalplural3),
                new IndexedColumn(FN.cundizionalindirectsing1),
                new IndexedColumn(FN.cundizionalindirectsing2),
                new IndexedColumn(FN.cundizionalindirectsing3),
                new IndexedColumn(FN.cundizionalindirectplural1),
                new IndexedColumn(FN.cundizionalindirectplural2),
                new IndexedColumn(FN.cundizionalindirectplural3),
                new IndexedColumn(FN.participperfectms),
                new IndexedColumn(FN.participperfectfs),
                new IndexedColumn(FN.participperfectmp),
                new IndexedColumn(FN.participperfectfp),
                new IndexedColumn(FN.participperfectmspredicativ),
                new IndexedColumn(FN.imperativSing),
                new IndexedColumn(FN.imperativPlural),
                new IndexedColumn(FN.imperativ3),
                new IndexedColumn(FN.imperativ4),
                new IndexedColumn(FN.imperativ5),
                new IndexedColumn(FN.imperativ6),
                new IndexedColumn(FN.gerundium),
                new IndexedColumn(FN.futursing1),
                new IndexedColumn(FN.futursing2),
                new IndexedColumn(FN.futursing3),
                new IndexedColumn(FN.futurplural1),
                new IndexedColumn(FN.futurplural2),
                new IndexedColumn(FN.futurplural3),
                new IndexedColumn(FN.futurdubitativsing1),
                new IndexedColumn(FN.futurdubitativsing2),
                new IndexedColumn(FN.futurdubitativsing3),
                new IndexedColumn(FN.futurdubitativplural1),
                new IndexedColumn(FN.futurdubitativplural2),
                new IndexedColumn(FN.futurdubitativplural3),

                new IndexedColumn(FN.preschentsing1enclitic),
                new IndexedColumn(FN.preschentsing2enclitic),
                new IndexedColumn(FN.preschentsing3encliticm),
                new IndexedColumn(FN.preschentsing3encliticf),
                new IndexedColumn(FN.preschentplural1enclitic),
                new IndexedColumn(FN.preschentplural2enclitic),
                new IndexedColumn(FN.preschentplural3enclitic),
                new IndexedColumn(FN.imperfectsing1enclitic),
                new IndexedColumn(FN.imperfectsing2enclitic),
                new IndexedColumn(FN.imperfectsing3encliticm),
                new IndexedColumn(FN.imperfectsing3encliticf),
                new IndexedColumn(FN.imperfectplural1enclitic),
                new IndexedColumn(FN.imperfectplural2enclitic),
                new IndexedColumn(FN.imperfectplural3enclitic),
                new IndexedColumn(FN.cundizionalsing1enclitic),
                new IndexedColumn(FN.cundizionalsing2enclitic),
                new IndexedColumn(FN.cundizionalsing3encliticm),
                new IndexedColumn(FN.cundizionalsing3encliticf),
                new IndexedColumn(FN.cundizionalplural1enclitic),
                new IndexedColumn(FN.cundizionalplural2enclitic),
                new IndexedColumn(FN.cundizionalplural3enclitic),
                new IndexedColumn(FN.futursing1enclitic),
                new IndexedColumn(FN.futursing2enclitic),
                new IndexedColumn(FN.futursing3encliticm),
                new IndexedColumn(FN.futursing3encliticf),
                new IndexedColumn(FN.futurplural1enclitic),
                new IndexedColumn(FN.futurplural2enclitic),
                new IndexedColumn(FN.futurplural3enclitic),
                new IndexedColumn(FN.futurdubitativsing1enclitic),
                new IndexedColumn(FN.futurdubitativsing2enclitic),
                new IndexedColumn(FN.futurdubitativsing3encliticm),
                new IndexedColumn(FN.futurdubitativsing3encliticf),
                new IndexedColumn(FN.futurdubitativplural1enclitic),
                new IndexedColumn(FN.futurdubitativplural2enclitic),
                new IndexedColumn(FN.futurdubitativplural3enclitic),
                new IndexedColumn(FN.composedWith),

                // nouns
                new IndexedColumn(FN.baseForm),
                new IndexedColumn(FN.mSingular),
                new IndexedColumn(FN.fSingular),
                new IndexedColumn(FN.mPlural),
                new IndexedColumn(FN.fPlural),
                new IndexedColumn(FN.pluralCollectiv),

                // adjectives
                new IndexedColumn(FN.adverbialForm),

                // other
                new IndexedColumn(FN.otherForm1),
                new IndexedColumn(FN.otherForm2),
                new IndexedColumn(FN.otherForm3),
                new IndexedColumn(FN.otherForm4),

                // automatic generation of forms
                new IndexedColumn(FN.automaticChange)
        );
    }
}
