package ch.pledarigrond.lucene.util;

import ch.pledarigrond.common.data.common.LemmaVersion;
import ch.pledarigrond.common.data.lucene.FieldType;
import ch.pledarigrond.common.data.lucene.IndexedColumn;

import java.util.Arrays;
import java.util.List;

public class DatabaseFields {
    public static List<IndexedColumn> getDatabaseColumns() {
        return Arrays.asList(
                new IndexedColumn("DStichwort", FieldType.STRING_SORTED),
                new IndexedColumn("DStichwort_sort", FieldType.INTEGER_SORTED),
                new IndexedColumn("DSemantik"),
                new IndexedColumn("DSubsemantik", FieldType.STRING_SORTED),
                new IndexedColumn("DGrammatik", FieldType.STRING_SORTED),
                new IndexedColumn("DGenus", FieldType.STRING_SORTED),
                new IndexedColumn("DStatus"),
                new IndexedColumn("DTags"),
                new IndexedColumn("RStichwort", FieldType.STRING_SORTED),
                new IndexedColumn("RStichwort_sort", FieldType.INTEGER_SORTED),
                new IndexedColumn("RSemantik"),
                new IndexedColumn("RSubsemantik", FieldType.STRING_SORTED),
                new IndexedColumn("RGrammatik", FieldType.STRING_SORTED),
                new IndexedColumn("RGenus", FieldType.STRING_SORTED),
                new IndexedColumn("RFlex"),
                new IndexedColumn("RTags"),
                new IndexedColumn("RInflectionType"),
                new IndexedColumn("RInflectionSubtype"),
                new IndexedColumn("categories", FieldType.SEMICOLON_SEPERATED),
                new IndexedColumn("DRedirect"),
                new IndexedColumn("RRedirect"),
                new IndexedColumn("user_comment"),
                new IndexedColumn("user_email"),
                new IndexedColumn("REtymologie"),
                new IndexedColumn("examples"),
                new IndexedColumn("RPronunciation"),

                // verbs
                new IndexedColumn("irregular"),
                new IndexedColumn("infinitiv"),
                new IndexedColumn("preschentsing1"),
                new IndexedColumn("preschentsing2"),
                new IndexedColumn("preschentsing3"),
                new IndexedColumn("preschentplural1"),
                new IndexedColumn("preschentplural2"),
                new IndexedColumn("preschentplural3"),
                new IndexedColumn("imperfectsing1"),
                new IndexedColumn("imperfectsing2"),
                new IndexedColumn("imperfectsing3"),
                new IndexedColumn("imperfectplural1"),
                new IndexedColumn("imperfectplural2"),
                new IndexedColumn("imperfectplural3"),
                new IndexedColumn("conjunctivsing1"),
                new IndexedColumn("conjunctivsing2"),
                new IndexedColumn("conjunctivsing3"),
                new IndexedColumn("conjunctivplural1"),
                new IndexedColumn("conjunctivplural2"),
                new IndexedColumn("conjunctivplural3"),
                new IndexedColumn("conjunctiv2sing1"),
                new IndexedColumn("conjunctiv2sing2"),
                new IndexedColumn("conjunctiv2sing3"),
                new IndexedColumn("conjunctiv2plural1"),
                new IndexedColumn("conjunctiv2plural2"),
                new IndexedColumn("conjunctiv2plural3"),
                new IndexedColumn("cundizionalsing1"),
                new IndexedColumn("cundizionalsing2"),
                new IndexedColumn("cundizionalsing3"),
                new IndexedColumn("cundizionalplural1"),
                new IndexedColumn("cundizionalplural2"),
                new IndexedColumn("cundizionalplural3"),
                new IndexedColumn("cundizionalindirectsing1"),
                new IndexedColumn("cundizionalindirectsing2"),
                new IndexedColumn("cundizionalindirectsing3"),
                new IndexedColumn("cundizionalindirectplural1"),
                new IndexedColumn("cundizionalindirectplural2"),
                new IndexedColumn("cundizionalindirectplural3"),
                new IndexedColumn("participperfectms"),
                new IndexedColumn("participperfectfs"),
                new IndexedColumn("participperfectmp"),
                new IndexedColumn("participperfectfp"),
                new IndexedColumn("participperfectmspredicativ"),
                new IndexedColumn("imperativ1"),
                new IndexedColumn("imperativ2"),
                new IndexedColumn("imperativ3"),
                new IndexedColumn("imperativ4"),
                new IndexedColumn("imperativ5"),
                new IndexedColumn("imperativ6"),
                new IndexedColumn("gerundium"),
                new IndexedColumn("futursing1"),
                new IndexedColumn("futursing2"),
                new IndexedColumn("futursing3"),
                new IndexedColumn("futurplural1"),
                new IndexedColumn("futurplural2"),
                new IndexedColumn("futurplural3"),
                new IndexedColumn("futurdubitativsing1"),
                new IndexedColumn("futurdubitativsing2"),
                new IndexedColumn("futurdubitativsing3"),
                new IndexedColumn("futurdubitativplural1"),
                new IndexedColumn("futurdubitativplural2"),
                new IndexedColumn("futurdubitativplural3"),

                new IndexedColumn("preschentsing1enclitic"),
                new IndexedColumn("preschentsing2enclitic"),
                new IndexedColumn("preschentsing3encliticm"),
                new IndexedColumn("preschentsing3encliticf"),
                new IndexedColumn("preschentplural1enclitic"),
                new IndexedColumn("preschentplural2enclitic"),
                new IndexedColumn("preschentplural3enclitic"),
                new IndexedColumn("imperfectsing1enclitic"),
                new IndexedColumn("imperfectsing2enclitic"),
                new IndexedColumn("imperfectsing3encliticm"),
                new IndexedColumn("imperfectsing3encliticf"),
                new IndexedColumn("imperfectplural1enclitic"),
                new IndexedColumn("imperfectplural2enclitic"),
                new IndexedColumn("imperfectplural3enclitic"),
                new IndexedColumn("cundizionalsing1enclitic"),
                new IndexedColumn("cundizionalsing2enclitic"),
                new IndexedColumn("cundizionalsing3encliticm"),
                new IndexedColumn("cundizionalsing3encliticf"),
                new IndexedColumn("cundizionalplural1enclitic"),
                new IndexedColumn("cundizionalplural2enclitic"),
                new IndexedColumn("cundizionalplural3enclitic"),
                new IndexedColumn("futursing1enclitic"),
                new IndexedColumn("futursing2enclitic"),
                new IndexedColumn("futursing3encliticm"),
                new IndexedColumn("futursing3encliticf"),
                new IndexedColumn("futurplural1enclitic"),
                new IndexedColumn("futurplural2enclitic"),
                new IndexedColumn("futurplural3enclitic"),
                new IndexedColumn("futurdubitativsing1enclitic"),
                new IndexedColumn("futurdubitativsing2enclitic"),
                new IndexedColumn("futurdubitativsing3encliticm"),
                new IndexedColumn("futurdubitativsing3encliticf"),
                new IndexedColumn("futurdubitativplural1enclitic"),
                new IndexedColumn("futurdubitativplural2enclitic"),
                new IndexedColumn("futurdubitativplural3enclitic"),
                new IndexedColumn("composedWith"),

                // nouns
                new IndexedColumn("mSingular"),
                new IndexedColumn("fSingular"),
                new IndexedColumn("mPlural"),
                new IndexedColumn("fPlural"),
                new IndexedColumn("pluralCollectiv"),

                // adjectives
                new IndexedColumn("adverbialForm"),

                // other
                new IndexedColumn("otherForm1"),
                new IndexedColumn("otherForm2"),
                new IndexedColumn("otherForm3"),
                new IndexedColumn("otherForm4"),

                // automatic generation of forms
                new IndexedColumn(LemmaVersion.AUTOMATIC_CHANGE),

                // contains all field-names of the current entry. This is used to search for non-existing fields:
                // https://kuzminva.wordpress.com/2017/04/04/lucene-field-does-not-exist/
                new IndexedColumn(LemmaVersion.FIELD_NAMES)
        );
    }
}
